const spices = [
    "5 spice powder",
    "adobo sauce",
    "ajwain",
    "allspice",
    "amchur",
    "asafoetida",
    "asafoetida powder",
    "baharat",
    "berbere",
    "bouquet garni",
    "cajun seasoning",
    "caraway seed",
    "cardamom",
    "cardamom pods",
    "cayenne pepper",
    "chili paste",
    "chili powder",
    "chili sauce",
    "chilis",
    "chipotle chilies in adobo",
    "chipotle chilies",
    "cinnamon roll",
    "cinnamon stick",
    "cinnamon sugar",
    "clove",
    "coriander",
    "coriander seeds",
    "cream of tartar",
    "cumin seeds",
    "curry leaves",
    "curry powder",
    "dill",
    "dried basil",
    "dried dill",
    "dried onion",
    "dried rubbed sage",
    "dried thyme",
    "fenugreek leaf",
    "fenugreek seeds",
    "garam masala",
    "garlic powder",
    "ground allspice",
    "ground ancho chili",
    "ground chipotle chile pepper",
    "ground cinnamon",
    "ground cloves",
    "ground coriander seeds",
    "ground cumin",
    "ground ginger",
    "ground mace",
    "ground nutmeg",
    "ground pepper",
    "ground red pepper",
    "ground sage",
    "ground turmeric",
    "harissa",
    "herbes de provence",
    "italian seasoning",
    "jaggery",
    "madras curry powder",
    "mint chutney",
    "nutmeg",
    "old bay seasoning",
    "oregano",
    "paprika",
    "pepper",
    "poppy seeds",
    "powdered sugar",
    "ras el hanout",
    "red pepper flakes",
    "red pepper powder",
    "rosemary",
    "rub",
    "saffron threads",
    "sage",
    "sage leaves",
    "seasoned salt",
    "shichimi togarashi",
    "smoked paprika",
    "sriracha sauce",
    "taco seasoning mix",
    "tarragon",
    "thai basil",
    "thai red curry paste",
    "thyme",
    "turmeric"
];

const fruits = [
    "acorn squash",
    "apple",
    "apricot",
    "banana",
    "berries",
    "cantaloupe",
    "cherry",
    "cranberries",
    "date",
    "figs",
    "grapefruit",
    "grapes",
    "kiwi",
    "lemon",
    "lime",
    "mango",
    "orange",
    "papaya",
    "peach",
    "pear",
    "pineapple",
    "plum",
    "pomegranate",
    "raisins",
    "rhubarb",
    "strawberries",
    "watermelon"
];

const vegetables = [
    "acorn squash",
    "artichoke heart quarters",
    "artichokes",
    "arugula",
    "asparagus spears",
    "avocado",
    "baby bok choy",
    "baby carrots",
    "baby corn",
    "baby spinach leaves",
    "bell pepper",
    "bok choy",
    "broccoli",
    "broccoli florets",
    "brussel sprouts",
    "cabbage",
    "carrots",
    "cauliflower",
    "cauliflower florets",
    "celery",
    "celery ribs",
    "celery root",
    "cherry tomatoes",
    "chile pepper",
    "collard greens",
    "corn",
    "cucumber",
    "daikon",
    "eggplant",
    "english cucumber",
    "fennel",
    "fennel bulb",
    "fennel seeds",
    "garlic",
    "ginger",
    "green beans",
    "green bell pepper",
    "jicama",
    "kale",
    "leeks",
    "lettuce",
    "mushroom",
    "napa cabbage",
    "okra",
    "onion",
    "parsley",
    "parsnip",
    "peas",
    "pepper",
    "potatoes",
    "pumpkin",
    "radicchio",
    "radishes",
    "red cabbage",
    "red onion",
    "romaine lettuce",
    "rutabaga",
    "shallot",
    "snap peas",
    "spinach",
    "squash",
    "sweet potatoes",
    "swiss chard",
    "tomatillo",
    "tomato",
    "turnip",
    "watercress",
    "winter squash",
    "yam",
    "yellow squash",
    "zucchini"
];

const proteins = [
    "anchovies",
    "bacon",
    "beef",
    "black beans",
    "chicken",
    "chorizo",
    "clams",
    "crab",
    "duck",
    "fish",
    "ham",
    "italian sausage",
    "lamb",
    "lobster",
    "pancetta",
    "pepperoni",
    "pork",
    "prosciutto",
    "salami",
    "sausage",
    "scallops",
    "shrimp",
    "spam",
    "squid",
    "steak",
    "tilapia",
    "tuna",
    "turkey",
    "venison"
];

const dairy = [
    "american cheese",
    "brie",
    "butter",
    "buttermilk",
    "cheddar cheese",
    "cheese",
    "cottage cheese",
    "cream cheese",
    "feta cheese",
    "fontina cheese",
    "gouda cheese",
    "gruyere cheese",
    "mozzarella cheese",
    "parmesan cheese",
    "ricotta cheese",
    "sour cream",
    "swiss cheese",
    "yogurt"
];

const grains = [
    "barley",
    "bread",
    "bread crumbs",
    "brown rice",
    "cereal",
    "corn tortillas",
    "cornmeal",
    "couscous",
    "crackers",
    "english muffin",
    "flatbread",
    "flour",
    "graham crackers",
    "lasagna noodles",
    "macaroni",
    "oats",
    "pasta",
    "pastry dough",
    "pita bread",
    "polenta",
    "popcorn",
    "quinoa",
    "rice",
    "rolled oats",
    "spaghetti",
    "tortillas",
    "white bread",
    "whole wheat bread"
];

const liquids = [
    "beer",
    "bouillon",
    "brandy",
    "chicken broth",
    "coconut milk",
    "coffee",
    "cola",
    "cointreau",
    "cognac",
    "cointreau",
    "condensed milk",
    "gin",
    "kahlua",
    "lemon juice",
    "lime juice",
    "margarita mix",
    "milk",
    "orange juice",
    "pineapple juice",
    "red wine",
    "rice vinegar",
    "rum",
    "sake",
    "soda",
    "soy sauce",
    "tequila",
    "vodka",
    "water",
    "white wine",
    "whiskey",
    "wine",
    "worcestershire sauce",
    "coconut oil",
    "coconut water",
    "evaporated milk",
    "oil",
    "olive oil",
    "peanut oil",
    "pesto",
    "vegetable oil",
    "vinegar",
    "syrup",
    "cider vinegar"
];

const other = [
    "agave nectar",
    "almond butter",
    "almond extract",
    "baking powder",
    "baking soda",
    "bread flour",
    "brown sugar",
    "cane sugar",
    "capers",
    "caramel sauce",
    "cardamom powder",
    "cashew butter",
    "chili paste",
    "chocolate",
    "chocolate chips",
    "cinnamon",
    "coconut",
    "cornstarch",
    "cream of coconut",
    "cream of mushroom soup",
    "dark chocolate",
    "fish sauce",
    "flaxseed",
    "flour tortillas",
    "frosting",
    "hazelnuts",
    "honey",
    "jam",
    "jelly",
    "ketchup",
    "maple syrup",
    "marinara sauce",
    "marshmallow",
    "marshmallow fluff",
    "molasses",
    "mustard",
    "nut butter",
    "nutella",
    "palm sugar",
    "panko",
    "peanut butter",
    "pie crust",
    "pistachios",
    "pizza crust",
    "powdered sugar",
    "pureed tomato",
    "rice flour",
    "rice noodles",
    "shortening",
    "soy milk",
    "tapioca",
    "tomato paste",
    "tomato sauce",
    "vanilla extract",
    "vanilla paste",
    "walnuts",
    "white chocolate",
    "white sugar",
    "whole wheat flour",
    "yeast"
];